// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  datasource: {
      // Port 5432 (Direct) for migrations and db push
      url: process.env.DIRECT_URL,
    },
  migrations: {
      seed: 'npx tsx prisma/seed.ts',
  },
});
